config/routes.rb
Rails.application.routes.draw do
  get 'note/index'
  devise_for :users
  # root path
  #root "home#index"
  devise_scope :user do
    root  'devise/sessions#new'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/note', to: 'note#index', as: :note
  get '/note/new', to: 'note#new', as: :new_note
  post '/note/new', to: 'note#create', as: :note_create
  get '/note/edit', to: 'note#edit', as: :note_edit
  patch 'note/update', to: 'note#update', as: :note_update
  get '/note/show', to: 'note#show', as: :note_show

  delete "note_delete", to: "note#destroy"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    private

  def after_sign_in_path_for(resource)
    note_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/note_controller.rb
class NoteController < ApplicationController
  
  def index
    @notes = current_user.notes.includes(:user)
  
    # user select date filter for notes
    if params[:start_date].present?
      start_date = Date.parse(params[:start_date])
      @notes = @notes.where("DATE(created_at) = ?", start_date)
    end
  end
  
  
  # for create new note
  def new
    @note = Note.new
  end
  
  # for save new note in database
  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to note_path
      
    else
      render :new
      # p "does not save data"
      puts @note.errors.full_messages
    end
  end
  


  def edit
    p params
    if params[:id].present?
      @note = Note.find(params[:id])
      p @note
    else
      redirect_to note_path, alert: "Note not found"
      
    end
  end
  
  

  def update

    @note = Note.find(params[:note][:id])
    if @note.update(note_params)
      redirect_to note_path(@note)
    else
      render :edit
    end
  end
  

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to note_path
  end
  
  private
  
  def note_params
    params.require(:note).permit(:title, :content).merge(user_id: current_user.id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noteapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   
    <%= stylesheet_link_tag "note", "data-turbo-track": "reload" %>


    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    

  </head>

  <body>
  <%= render partial: "shared/notice" %>
  <%= render partial: "shared/alert" %>
    <%= yield %>
  </body>
</html>

app/views/note/_note_empty.html.erb
<div class="note-container">

    <div class = "empty-notes-page">

        <div class="empty-img">
        <%= image_tag asset_path('empty_image.png'), alt: 'truemark_logo' %>
        </div>

        <div> 
            <h2> You don't have any notes yet </h2>
        </div>

        <div>
            <p> Please add the note by clicking the add note button</p>
        </div>

        <%= link_to new_note_path do %>
            <div class="add-note-buttom empty-button">        
            <i class='bx bx-plus icon'></i>
                <p class="text">Add Note</p>
            
            </div>
            <% end %>

    </div>
</div>

app/views/note/_note_form.html.erb
<div class="note-container">
              <% @notes.each do |note| %>
                <div class="notes">
                    <div class="top-notes">
                        <div class="left-top-notes">
                          <p><%= note.title %></p>
                        </div>

                        <div class="right-top-notes">
                            <p><%= note.created_at.strftime('%d- %B -%Y')%></p>
                            <div class="dots"><i class='bx bx-dots-vertical-rounded '></i>
                                <div class="dropdown">
                                  <ul>
                                  <%= link_to note_edit_path(id: note.id) do %>
                                    <li>        
                                    <i class='bx bxs-edit'></i>
                                        <p>Edit</p>
                                    </li>
                                    <% end %>
                                    <%= link_to note_delete_path(id: note.id), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }  do %>
                                      <li>        
                                      <i class='bx bx-trash' ></i>
                                          <p>Delete</p>
                                      </li>
                                      <% end %>
                                  </ul>
                                </div>

                            </div>
                        </div>

                       
                    </div>
                    

                    <div class="notes-content">

                      <p><%= note.content %></p>
                      
                    </div>
                </div>
              <% end %>
             

        </div>

app/views/note/edit.html.erb
<h1>Edit Note</h1>

<%= form_with(model: @note, url: note_update_path(@note), method: :patch) do |form| %>
    <%= form.hidden_field :id %>

  
    <%= form.label :title %>
    <%= form.text_field :title %>
  
    <%= form.label :content %>
    <%= form.text_area :content %>
  
    <%= form.submit %>
  <% end %>
  

app/views/note/index.html.erb
<div class="body">

  <div class="navbar">
      <div class="left-navbar">
      <%= image_tag asset_path('logo.png'), alt: 'truemark_logo' %>
      </div>

      <div class="right-navbar">
      <%= button_to  destroy_user_session_path, method: :delete,class:"btn btn-danger", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }  do %>
           <span> Logout</span>
        <% end %>
      </div>

  </div>

  <div class="container1">

    <div class="main-container">
          
        <div class="top-container">
            <div class="left-top-container">
                <p>Notes</p>
            </div>

            <div class="right-top-container">
              <div class="filter"> Filter by: </div>
             
              <%= form_tag note_path, method: :get do %>
                <div>
                  <%= date_field_tag :start_date, params[:start_date], onchange: "this.form.submit();" , class: "my-date-field"%>
                </div>
              <% end %>

              <% if @notes.present? %>
                    <%= link_to new_note_path do %>
                    <div class="add-note-buttom">        
                    <i class='bx bx-plus icon'></i>
                        <p class="text">Add Note</p>
                      
                    </div>
                    <% end %>
              <% end %>
          
            </div>
        </div>
        <% if @notes.empty? %>
           <%= render partial: "note_empty" %>
        <% else %>
            <%= render partial: "note_form" %>
       <% end %>
      
    
    </div>
  </div>

</div>

app/views/note/new.html.erb
<%= form_with(model: @note, url: note_create_path) do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
    <div>
      <%= form.submit "Create Note" %>
    </div>
  <% end %>
  

app/views/shared/_alert.html.erb
<% if alert %>
  <div class="notice-alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="notice-alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <%= notice %>
  </div>
<% end %>